## 1) List Operations:

In [21]:
# List of integers containing numbers from 1 to 10.
list_of_integers = [i for i in range(1, 11)]

# Appending the square of each number to the list.
list_of_integers += [i*i for i in range(1, 11)]

# Finding the sum of all elements in the list.
sum_of_list = sum(list_of_integers)

print (list_of_integers)
print (sum_of_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
440

## 2) Tuple Operations:

In [22]:
# Tuple containing the first five even numbers.
even_numbers_tuple = (2, 4, 6, 8, 10)

# Finding the product of all elements in the tuple.
product_of_evens = even_numbers_tuple[0] * even_numbers_tuple[1] * even_numbers_tuple[2] * even_numbers_tuple[3] * even_numbers_tuple[4]

print (even_numbers_tuple)
print (product_of_evens)

(2, 4, 6, 8, 10)
3840

## 3) Set Operations:

In [23]:
# Two sets of odd numbers between 1 to 10.
odd_set_1 = {1, 3, 5}
odd_set_2 = {5, 7, 9}

# Finding the union and intersection of the two sets.
odd_set_union = odd_set_1.union(odd_set_2)
odd_set_intersection = odd_set_1.intersection(odd_set_2)

print (odd_set_1)
print (odd_set_2)
print (odd_set_union)
print (odd_set_intersection)

{1, 3, 5}
{9, 5, 7}
{1, 3, 5, 7, 9}
{5}

## 4) Dictionary Operations:

In [24]:
# A dictionary with the first five lowercase alphabets and their ASCII values.
values = {chr(97 + i): 97 + i for i in range(5)}

print (values)

{'a': 97, 'b': 98, 'c': 99, 'd': 100, 'e': 101}

## 5) Functional Programming:

In [25]:
# A function to square a number.
def square(x):
    return x * x

# Using map to apply the square function to each element from 1 to 10.
squared_numbers = list(map(square, range(1, 11)))

print (squared_numbers)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]